### ISSUE TITLE
glad to learn your article

### ISSUE THREAD

**Issue by Rossichan** [declare-lab/SANCL#2]
I'm very  interested  in your article, expect your code updating! So when it come?

**Comment by Clement25** [comment]
Hi Rossichan. I am also very eager to share my code, only to wait for the company's permission. I will work on this after the current project's deadline (Jan 2023). Additionally you can refer to this [repository](https://github.com/jhliu17/MCR) since this is my code base.

**Comment by Rossichan** [comment]
Thanks for your response and look forward to your results!

**Comment by Clement25** [comment]
> Thanks for your response and look forward to your results!

Hi, Rossichan. We have uploaded the code just now.

**Comment by Rossichan** [comment]
It's so surprised your project becomes complete, and i have some trouble after enjoying your work, such as what's the processing data step1: the raw log file , i can't find it

**Comment by Clement25** [comment]
> It's so surprised your project becomes complete, and i have some trouble after enjoying your work, such as what's the processing data step1: the raw log file , i can't find it

Hi Rossichan. Sorry for replying late. I am not sure what do you mean by "raw log file"? Could you elaborate more? You may directly download the whole processed dataset instead
