### ISSUE TITLE
Dissertation reproduction work questions

### ISSUE THREAD

**Issue by APPLE-XMT** [declare-lab/SANCL#3]
Hello, it is a great honor to read your article. When I am doing the recurrence work, I always use the learning rate in the config file to achieve the best results in the 1-2 epoch. Is this correct?

**Comment by Clement25** [comment]
It's very normal to converge within 5 epochs since the dataset is very huge.

**Comment by APPLE-XMT** [comment]
ok thanks for your answer

**Comment by APPLE-XMT** [comment]
Hello, I see that you mentioned in the paper that the label range of the dataset is 0-4, but I found that there is no label of 0 in the amazon dataset. Why is this?

**Comment by Clement25** [comment]
I also found this and don't know either.
